[".zprezto"]
type = "git-repo"
url = "https://github.com/sorin-ionescu/prezto.git"
refreshPeriod = "168h"

[".zprezto".pull]
args = ["--recurse-submodules"]

[".zprezto".clone]
args = ["--recursive"]

[".zprezto/contrib/fzf"]
type = "git-repo"
url = "https://github.com/gpanders/fzf-prezto.git"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"