if empty(globpath(&rtp, 'autoload/plug.vim')) && !has('nvim')
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
elseif empty(glob('~/.local/share/nvim/site/autoload/plug.vim')) && has('nvim')
    silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

source ~/.vim/configs/preamble.vimrc

call plug#begin()

source ~/.vim/configs/editor.vimrc

source ~/.vim/configs/autocomplete.vimrc

source ~/.vim/configs/latex.vimrc

source ~/.vim/configs/workspace.vimrc

source ~/.vim/configs/interface.vimrc

if !has('nvim')
    call plug#end()
endif

source ~/.vim/configs/postamble.vimrc

